# Generated by Django 5.1.5 on 2025-01-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('dataModel', models.IntegerField()),
                ('embeddingLayer', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Document Embedding',
                'verbose_name_plural': 'Document Embeddings',
                'db_table': 'embeddings',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['layer'], name='layer_idx'), models.Index(fields=['system'], name='system_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogUserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='کوئری کاربر')),
                ('selected_layers', models.JSONField(default=list, verbose_name='لایه\u200cهای انتخاب\u200cشده')),
                ('system', models.CharField(max_length=255, verbose_name='سازمان')),
                ('score', models.FloatField(verbose_name='امتیاز')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'نتایج جستجوی کاربر',
                'verbose_name_plural': 'نتایج جستجوهای کاربران',
                'db_table': 'log_user_search',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['query'], name='query_idx')],
            },
        ),
    ]
