# Generated by Django 5.1.5 on 2025-01-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logusersearch',
            name='score',
        ),
        migrations.RemoveField(
            model_name='logusersearch',
            name='system',
        ),
    ]
