# Generated by Django 5.1.5 on 2025-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_logusersearch_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logusersearch',
            name='selected_layers',
        ),
        migrations.AddField(
            model_name='logusersearch',
            name='relevance',
            field=models.IntegerField(default=0, verbose_name='مرتبط بودن با کوئری'),
        ),
        migrations.AddField(
            model_name='logusersearch',
            name='selected_layer',
            field=models.CharField(default='', max_length=255, verbose_name='لایه انتخاب شده'),
        ),
        migrations.AddField(
            model_name='logusersearch',
            name='selected_organization',
            field=models.CharField(default='', max_length=255, verbose_name='سازمان انتخاب شده'),
        ),
    ]
