# Generated by Django 5.1.5 on 2025-02-03 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_logusersearch_selected_layers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logusersearch',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='logusersearch',
            name='relevance',
            field=models.IntegerField(verbose_name='مرتبط بودن با کوئری'),
        ),
        migrations.AlterField(
            model_name='logusersearch',
            name='selected_layer',
            field=models.CharField(max_length=255, verbose_name='لایه انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='logusersearch',
            name='selected_organization',
            field=models.CharField(max_length=255, verbose_name='سازمان انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='logusersearch',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان'),
        ),
    ]
