# Generated by Django 5.1.5 on 2025-10-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_logusersearch_type_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbeddingTrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('dataModel', models.IntegerField()),
                ('embeddingLayer', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Document Embedding Train Model',
                'verbose_name_plural': 'Document Embeddings Train Models',
                'db_table': 'embeddingsTrainModel',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['layer'], name='train_model_layer_idx'), models.Index(fields=['system'], name='train_model_system_idx')],
            },
        ),
    ]
