# Generated by Django 5.1.5 on 2025-10-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_documentembeddingtrainmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentembeddingtrainmodel',
            table='embeddings_train_Model',
        ),
    ]
