# Generated by Django 5.1.5 on 2025-10-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_documentembeddingtrainmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentembeddingtrainmodel',
            name='embeddingLayer',
        ),
    ]
